### ISSUE TITLE
BattleScribe 2.0

### ISSUE THREAD

**Issue by Jonskichov** [BSData/The-9th-Age#75]
Hi guys.

BattleScribe 2.0 is coming and it contains some major changes to Data Editor and the data format.

While it should happily upgrade 1.15.x format data files to the new format, you never know what sneaky bugs might be lurking...

It would help a lot if you could run your data through it and make sure nothing gets broken so we have no nasty surprises on release day (whenever that might be...).

**Alpha Downloads:**
Desktop: https://github.com/BattleScribe/Desktop-Alphas/issues/1
Android: https://github.com/BattleScribe/Android-Alphas/issues/1
iOS: https://github.com/BattleScribe/iOS-Alphas/issues/1

If you find any issues, please do let me know: https://github.com/BattleScribe/Desktop-Alphas/issues

**Comment by Karanadon** [comment]
Just started looking at compatibility today. I'm having some trouble getting the min/max in roster to work correctly. Previously we had it set so that there was min 1 and max 1 general in an army. I can't work out where the restraints now need to go. I've tried a few things but it still seems to want everything that has the option of being the general to choose that option, even if they are not selected to include in the roster. Any ideas?

**Comment by Karanadon** [comment]
![battlescribe](https://cloud.githubusercontent.com/assets/18306729/18896404/f305dc12-857d-11e6-846b-d46bbd3fcb81.jpg)
Here is an example of what is happening, with the max in roster constraint selected.

**Comment by Arturius1** [comment]
Hey @Karanadon 

Have you read this?
https://github.com/BattleScribe/Desktop-Alphas/issues/1

"(One thing you will need to fix by hand is any shared entries that are linked at the root of a catalogue. If they have min/max values set, these values will be validated as "min/max in parent" which will kick up errors that you probably don't want. You will need to move Constraints from the shared entries to the appropriate root Links.)"

I've managed to fix that errors by moving and adjusting Army General from Shared Selection Entries to Saurian Warlord under Selection Entries. 
It will probably have to be repeated for every character that can be a general.

I'm attaching the file, extension changed to txt, please download and change back to .catz
[Saurian_Ancients fixed.txt](https://github.com/BSData/The-9th-Age/files/499216/Saurian_Ancients.fixed.txt)

**Comment by Karanadon** [comment]
I did read that but my brain couldn't make sense of it haha! Looks to be working the way you have it, so should be easy to convert files to the new format seeing as not much else changes.

**Comment by Arturius1** [comment]
Glad I could help :)

Since you had time to take a look at 2.0 @Karanadon I have some questions:

Does the new file format helps us - The  9th Age Tool Support - in any way?
For example, can we enter one common magic items list for use in all army-files?
Similar with common rules? 
Any groundbreaking changes or challenges?

If you wish we can continue this discussion on our forum via PM.
Art.

**Comment by amis92** [comment]
@Arturius1 yup, for your questions: BS2 allows shared entries, profiles and rules to be put in Game System file (.gst), which then are available for every catalogue in that game system.

**Comment by Arturius1** [comment]
That is a long awaited feature, and I am sure it will make many people happy.
Any idea when we can expect Battlescribe 2.0 public release?

**Comment by amis92** [comment]
Well, according to Jon and all signs and stars, and most importantly, as the first rule of software engineering says, Soon™. :/

**Comment by paulberridge** [comment]
2.0 was released yesterday and I installed the 9th age files. It's throwing an error about min/max % when I create a new roster for SE

**Comment by Jonskichov** [comment]
@paulberridge There was an issue that was causing some errors at startup that's fixed in 2.00.01.

Other than that, some min/max errors are expected right now. There's a situation which the app couldn't automatically resolve during data file upgrade. It'll need fixing manually.
